-   repo: local
    hooks:
    -   id: rust-linting
        name: Rust linting
        description: Run cargo fmt on files included in the commit. rustfmt should be installed before-hand.
        entry: cargo +nightly fmt --all --
        pass_filenames: true
        types: [file, rust]
        language: system
