[package]
name = "avro-rs"
version = "0.6.1"
authors = ["Flavien Raynaud <flavien.raynaud@gmail.com>", "Antonio Verardi <antonio.uccio.verardi@gmail.com>"]
description = "Library for working with Apache Avro in Rust"
license = "MIT"
readme = "README.md"
repository = "https://github.com/flavray/avro-rs"

[features]
snappy = ["byteorder", "crc", "snap"]

[dependencies]
byteorder = { version = "1.0.0", optional = true }
crc = { version = "1.3.0", optional = true }
failure = "0.1.1"
failure_derive = "0.1.1"
libflate = "0.1"
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
snap = { version = "0.2.3", optional = true }
