on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

name: Continuous Integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.40.0  # MSRV

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --all-targets

      - name: Build Benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --no-run --all-features --all-targets

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --all-targets
